[webservers]
web-1   ansible_host=89.169.159.12 fqdn=fhm17s90lfin6halofib.auto.internal
web-2   ansible_host=89.169.138.28 fqdn=fhmdvnq33ir0lc31khe5.auto.internal

[databases]
main   ansible_host=89.169.156.8 fqdn=fhm2hgabfh5cifcgdhh3.auto.internal
replica   ansible_host=89.169.135.222 fqdn=fhm8ue3alaor3vp350do.auto.internal

[storage]
storage   ansible_host=10.0.1.34 fqdn=fhmfsir68ck6jdh51d21.auto.internal
